# English renderings of TLHdig's German dictionary glosses (batch 1).
# Proper names are left unchanged. "(u. B.)" = unbekannter Bedeutung = meaning unknown.
G = {
"Gott": "god", "Zunge": "tongue", "wie": "as, how", "ein": "one, a", "Opfergrube": "offering pit",
"Zungenmodell": "tongue (model)", "warm sein": "be warm", "dieser": "this", "Grenze": "border",
"Göttlichkeit": "divinity", "Land": "land", "welcher": "which", "wer?": "who?", "(u. B.)": "(meaning unknown)",
"darin": "therein", "Gottheit": "deity", "dito": "ditto", "in": "in", "begeistert": "inspired",
"Wohlbefinden": "well-being", "nehmen": "take", "sterben": "die", "machen": "make, do", "setzen": "put, set",
"Hand": "hand", "noch": "still, further", "stehen": "stand", "kämmen": "comb", "lassen": "let, leave",
"hinein-": "in-", "Bild eines Berges": "image of a mountain", "weg": "away", "von… weg": "away from",
"weg-": "away-", "Haus": "house", "nicht": "not", "Wort": "word", "hinter": "behind", "sprechen": "speak",
"Seuche": "plague, epidemic", "danach": "afterwards", "dann": "then", "vor": "before", "krank sein": "be sick",
"Elle": "cubit", "vorderer": "front, first", "Körperteil": "(body part)", "auf": "on", "oben": "above",
"oben-": "up-", "dunkel": "dark", "fertig sein": "be finished", "Schaf": "sheep", "Mensch": "person, human",
"ordnen": "arrange", "zwei": "two", "er": "he", "übergeben": "hand over", "böse": "evil", "Luft": "air",
"Rind": "cattle, ox", "wieder": "again", "stehlen": "steal", "Krankheit": "illness", "weil": "because",
"Wettergott": "Storm-god", "Erde": "earth", "Herr": "lord", "in dieser Weise": "in this way", "werden": "become",
"krank": "sick", "gehen": "go", "Greisin": "Old Woman (ritual expert)", "Wein": "wine", "Ufer": "riverbank",
"zerbrechen": "break", "sitzen": "sit", "Mann": "man", "unten": "below", "bedecken": "cover", "fassen": "seize, hold",
"Männlichkeit": "manhood", "Halbmaß": "half-measure", "Priester": "priest", "sehen": "see",
"Sonne(ngottheit)": "Sun(-deity)", "Kopf": "head", "Tag (vergöttlicht)": "Day (deified)",
"Verbeugung(?)": "bow(?)", "Wolle": "wool", "jetzt": "now", "oder": "or", "Frau": "woman", "Volk": "people",
"Gottesbegeisterter(?)": "ecstatic(?)", "sein": "be", "jeder; ganz": "every; whole", "Truppe": "troops",
"Tag": "day", "viel": "much", "in Ordnung bringen; gut werden": "set right; get well", "unter": "under",
"unter-": "under-", "(Hohlmaß)": "(dry measure)", "krank machen": "make sick", "vor-": "fore-", "trinken": "drink",
"Opfer": "offering", "Quelle": "spring", "speichern": "store", "Kranker": "sick man", "Kranke": "sick woman",
"schlagen": "strike", "Inneres": "interior", "(Mond)licht(?) in UD SAKAR „Mondsichel“": "(moon)light(?), in UD.SAKAR 'crescent'",
"Menschheit": "humankind", "Tisch": "table", "irgendein": "any", "Herz": "heart", "(Gefäß)": "(a vessel)",
"Speicher": "storehouse", "Schilf": "reed", "(Brot oder Gebäck)": "(a bread or pastry)", "Heldenmut(?)": "valour(?)",
"Weg": "road", "Nacht": "night", "Emmer": "emmer wheat", "schreien": "cry out", "Kind": "child",
"REF1": "REF1 (particle)", "Gewand": "garment", "schütten": "pour (out)", "hinterer": "rear", "außerdem": "moreover",
"Becher": "cup", "kommen": "come", "Wort; Sache": "word; matter", "drei": "three", "heraus aus": "out of", "aus-": "out-",
"(sich) drehen": "turn", "wirken": "work, perform", "neun": "nine", "irgendwo": "somewhere", "Silber": "silver",
"ebenso": "likewise", "geben": "give", "waschen": "wash", "wahr": "true", "heben": "lift", "Buchsbaum": "boxwood",
"Mehl": "flour", "ich": "I", "rezitieren": "recite", "haben": "have", "zwölf": "twelve", "König": "king", "Zorn": "anger",
"Abgeschnittenes": "clipping, cut piece", "sobald als": "as soon as", "wo": "where", "schlafen": "sleep",
"Schlaf": "sleep", "vertrauen": "trust", "Unsauberkeit": "impurity", "Weinfunktionär": "wine official",
"umkommen": "perish", "hinschaffen": "bring there", "(Mond)licht(?)": "(moon)light(?)", "gegenüber": "opposite",
"klein": "small", "Wind": "wind", "(her)bringen": "bring (here)", "gänzlich": "entirely",
"schlachten/beschwören": "slaughter / conjure", "()": "", "erheben": "raise", "gut": "good", "Lehm": "clay, mud",
"Jahr": "year", "Satz": "clause", "Beinhaus(?)": "bone-house(?)", "Knochen": "bone", "Schulter": "shoulder",
"Seele": "soul", "wenig": "little", "irgendwie": "somehow", "ziehen": "pull, draw", "graben": "dig", "essen": "eat",
"vier": "four", "(Maßeinheit)": "(unit of measure)", "Ferkel": "piglet", "fliehen": "flee", "libieren": "libate, pour a libation",
"(Opferterminus)": "(offering term)", "Brotlaib": "loaf", "Brotopferer": "bread-offerer", "Herrschaft": "rule",
"treten": "step", "Fluss": "river", "groß": "great, large", "Lehmputz(?)": "clay plaster(?)", "Körper": "body",
"orakeln": "consult an oracle", "zur Stirn gehörig": "of the forehead", "zu": "to", "Versammlung": "assembly",
"Blut": "blood", "weiß": "white", "ein halb": "one half", "rufen": "call", "teilen": "divide", "Frevel": "offence, sacrilege",
"während": "while", "eine Zeitlang": "for a while", "Kindheit": "childhood", "schützen": "protect", "schmücken": "adorn",
"entfernen": "remove", "wahrlich": "truly", "Gefäß": "vessel", "heraufsprudeln": "bubble up",
"(übrig) bleiben": "remain (over)", "Berg": "mountain", "rot": "red", "kurz": "short", "spucken": "spit",
"Sehne": "sinew", "hören": "hear", "Wasser": "water", "(speerförmiges Brot oder Gebäck)": "(spear-shaped bread or pastry)",
"Nomade(?)": "nomad(?)", "Fuß": "foot", "Brocken": "morsel", "Auge": "eye", "schicken": "send", "Libation": "libation",
"Tontafel": "clay tablet", "gesamt": "all, total", "Feind": "enemy", "schwer werden": "become heavy", "des/der": "of the",
"laufen": "run", "wenn": "if, when", "ankommen": "arrive", "hinauf": "up", "Gleichrangiger": "equal, peer",
"Beschwörung": "incantation", "Großer": "great one, chief", "Paar": "pair", "Jahresfrist": "year's term", "Bier": "beer",
"Brot": "bread", "Fuß aus Holz": "wooden foot", "niederknien": "kneel", "Bronze": "bronze", "voll": "full",
"Vater": "father", "ihr": "you (pl.)", "schwören": "swear", "Pferd": "horse", "sich tummeln": "romp, move about",
"Ohr": "ear", "Freund": "friend", "(ERG) Seuche": "plague (ergative)", "hier": "here", "Mund": "mouth",
"zu Bergbewohnern gehörig": "of the mountain-dwellers", "zeugen": "beget", "lebendig": "alive", "Grütze": "groats, grits",
"fußförmiges Gefäß": "foot-shaped vessel", "Fingernagel": "fingernail", "früher": "formerly", "(Getreideart)": "(a cereal)",
"wenden": "turn", "du": "you", "Orakel": "oracle", "Stadt": "city", "füllen": "fill", "Winter": "winter",
"Palastbediensteter": "palace attendant", "Oberarm": "upper arm", "reinigen": "purify", "Samen": "seed",
"Behexung durch Zaubersprüche": "bewitchment by spells", "Mauer": "wall", "Schwur": "oath", "rechts": "right",
"dort; damals": "there; then", "Gefangener": "prisoner", "(Örtlichkeit?)": "(a locality?)", "freveln": "commit an offence",
"und": "and", "kultisch rein": "ritually pure", "drücken": "press", "Tote(ngeist)": "the dead (spirit)",
"Feindschaft": "enmity", "Himmel": "heaven, sky", "Pein": "pain, torment", "Leben": "life", "Tor": "gate",
"Käse": "cheese", "Figur": "figurine", "blau": "blue",
}
