# English renderings of TLHdig's German glosses (batch 4).
G = {
"gut werden": "get well", "(pflanzliche Substanz)": "(a plant substance)", "Teppich": "carpet",
"bitterer Knoblauch": "bitter garlic", "sich vermindern": "decrease", "SAG": "head (SAG)",
"(irdenes walḫi-Gefäß)": "(earthenware walḫi-vessel)", "Garten": "garden", "zur arni(t)-Pflanze gehörig": "of the arni(t)-plant",
"Weh": "woe, pain", "ölen": "oil, anoint", "Gesinde": "household servants", "Angst": "fear", "erhitzen": "heat",
"(zusammen) nähen": "sew (together)", "Kresse(?)": "cress(?)", "(Körperausscheidungen) fallen lassen(?)": "let fall (excretions)(?)",
"(Gemüse)": "(a vegetable)", "Penis": "penis", "beschnitten": "circumcised", "Vorhaut": "foreskin", "Beutel(?)": "bag(?)",
"Stern (vergöttlicht)": "Star (deified)", "Stern": "star", "Stern-Stein": "star-stone", "(Musikinstrument) blasen": "blow (an instrument)",
"innen befindlich": "inner", "Reinigung": "purification", "er starb": "he died", "Schleier(?)": "veil(?)",
"jetzt:ADV=CNJadd": "now (adv.) + 'and'", "Hülsenfrucht(?)": "legume(?)", "URU/KUR": "city/land", "Gerechter": "just one",
"zeigen": "show", "kultisches Fest": "cult festival", "Gebet": "prayer", "Mitleid haben(?)": "have pity(?)", "halt ein": "stop!",
"warm werden": "become warm", "Vorratsgefäß": "storage jar", "stolz": "proud", "hinstellen": "set up", "Kult": "cult",
"(hin)setzen": "set (down)", "komm (herbei?)": "come (here?)", "jenseits": "beyond", "Distrikt": "district", "Verwalter": "administrator",
"gegen jmd. rebellieren": "rebel against someone", "Bruder": "brother", "aufgehen": "rise", "küssen": "kiss", "hierher": "hither",
"Stab": "staff", "hochheben": "lift up", "Brotopferer(?)": "bread-offerer(?)", "zweiter": "second", "Vorderseite": "front side",
"gerade": "straight", "in Ordnung bringen; MP: gedeihen": "set right; (mid.) thrive", "so (wie erwähnt)": "so (as mentioned)",
"Rand": "edge", "zugrunde richten": "ruin", "billigen": "approve", "kraftstrotzend": "vigorous", "Maulesel": "mule",
"Truppe; Nomade": "troops; nomad", "(Stadt-)Mauer": "(city) wall", "grün Sein": "being green", "(Biersorte)": "(a kind of beer)",
"ritzen": "scratch, incise", "(breites) Band (aus Wolle)": "(broad) band (of wool)", "hell(?)": "bright(?)", "vereinzelt": "isolated",
"fallen": "fall", "beständige Felsanlage": "permanent rock installation", "Regen": "rain",
"Brot für die Verstorbenen": "bread for the dead", "ein Zehntel": "one tenth", "zerkleinert": "crushed", "Klumpen": "lump",
"salzen": "salt", "Salz": "salt", "elf": "eleven", "Spaten": "spade", "Krug": "jug", "(Krug)": "(a jug)", "zu Ende": "at an end",
"Schaden(?)": "damage(?)", "Speichel": "saliva", "zum (Vieh-)Aufkommen gehörig": "of the (livestock) yield", "wir": "we",
"stärken": "strengthen", "kräftig": "strong", "(ERG) Seite": "side (ergative)", "(ERG) Stiel": "stalk (ergative)",
"(ERG) Fingernagel": "fingernail (ergative)", "(ERG) Knochen": "bone (ergative)", "(Gegenstand) von blutroter Farbe": "(object) of blood-red colour",
"Weihung": "consecration", "packen": "grab", "-wärts": "-wards", "gefügig machen": "make compliant", "Schwere": "heaviness",
"süß werden": "become sweet", "(Baum oder Strauch)": "(a tree or shrub)", "Alter einer Greisin": "old age (of a woman)",
"von weitem": "from afar", "Ernte": "harvest", "Bauch": "belly", "Leere; Achselhöhle": "emptiness; armpit", "Gerät(e)": "implement(s)",
"Brennofen": "kiln", "Dach": "roof", "von dieser Seite": "from this side", "Bandwurmfinne(?)": "tapeworm cyst(?)",
"besprengen": "sprinkle", "aufgehend?": "rising?", "gären": "ferment", "Gurkenbrot": "cucumber bread", "Person": "person",
"werfen": "throw", "Truhe": "chest", "Weichteile(?)": "soft parts(?)", "groß machen": "enlarge", "schmelzen": "melt",
"gelb": "yellow", "gelb werden": "turn yellow", "auf der Oberseite": "on the upper side", "Tierhaar": "animal hair",
"(Art Haar)": "(a kind of hair)", "zehntausend": "ten thousand", "Schafhirt": "shepherd", "Rinderhirt": "cowherd",
"Nachkommenschaft": "offspring", "Nachkommen nach Nachkommen": "descendants upon descendants", "sägen": "saw",
"Gesundheit": "health", "schreiben": "write", "weiden": "graze", "Läufer": "runner", "Zustand der Pein": "state of torment",
"Bedrückung": "oppression", "Unreinheit": "impurity", "über": "over", "hinüber-": "across-", "dritt-": "third",
"ängstigen": "frighten", "vorn": "in front", "König werden": "become king", "nüchtern": "sober, fasting", "Ration(?)": "ration(?)",
"(u.B.)": "(meaning unknown)", "n+3": "n+3", "Kampf": "battle", "Sonnenscheibe(?)": "sun disc(?)",
"Wachsendes(?) in UD SAKAR „Mondsichel“": "waxing(?), in UD.SAKAR 'crescent'", "fett": "fat", "(Baum, und dessen Frucht)": "(a tree and its fruit)",
"unreife Dattel": "unripe date", "hattisch": "Hattic", "täglich": "daily", "rühmen": "praise", "(Besänftigungsmittel)": "(an appeasement substance)",
"angenehm": "pleasant", "Holztafelschreiber": "wooden-tablet scribe", "Kommissär": "commissioner", "(Kleidungsstück)": "(an item of clothing)",
"Wettergott-Mann": "Storm-god man (functionary)", "Gewandnadel": "garment pin", "ausgelegt": "laid out", "Gerstenbreisuppe": "barley-porridge soup",
"Ohrring": "earring", "Kulttänzer": "cult dancer", "Ring": "ring", "22": "22", "(im Ritual verwendetes Tuch)": "(a cloth used in ritual)",
"(Ständer)": "(a stand)", "33": "33", "Schmalz": "lard", "Siegel": "seal", "Fettbrot": "fat bread", "Ölbaum": "olive tree",
"Pflock": "peg", "Sesam": "sesame", "(Obstbaum und seine Frucht?)": "(a fruit tree and its fruit?)", "sich sättigen": "eat one's fill",
"erst-": "first", "(Tuch)": "(a cloth)", "Starker": "strong one", "36": "36", "29": "29", "(Festgewand)": "(a festive garment)",
"(Getränk)": "(a drink)", "Löffel": "spoon", "Niere": "kidney", "Kleidungsstück mit Scheiben verziert": "garment decorated with discs",
"(sehr) groß": "(very) great", "zermalmen": "grind, crush", "Rute": "rod", "erster": "first", "Palastbeamter": "palace official",
"(Kraut)": "(a herb)", "ach!": "alas!", "rot werden": "turn red", "Schwäche(?)": "weakness(?)", "Stufe": "step",
"Verunreinigung": "contamination", "Zypresse": "cypress", "Herrin": "lady, mistress", "Gänze": "entirety", "Bart": "beard",
"Urin": "urine", "Obsidian": "obsidian", "vorüberziehen; verschwinden lassen": "pass by; make disappear",
"Skorpion (Sternbild)": "Scorpion (constellation)", "Dattel": "date (fruit)", "allmählich hell werden": "gradually grow light",
"Gazelle": "gazelle", "(Stadttor)": "(a city gate)", "Tamariske": "tamarisk", "Zeder": "cedar", "mischen": "mix",
"niederknien lassen": "make kneel", "soviel wie": "as much as", "ebenso zahlreich": "equally numerous", "kalt werden": "grow cold",
"(Gartenpflanze)": "(a garden plant)", "Gartenlauch": "garden leek", "Loch": "hole", "Wurzel": "root", "Leopard": "leopard",
"Leopardenmann": "leopard-man (cult functionary)", "(be)spritzen": "splash", "(Jagdtier?)": "(a game animal?)", "tropfen": "drip",
"Wickel(?)": "compress, wrap(?)", "nachts": "at night", "eintauchen": "dip", "Blei": "lead", "groß werden": "grow up",
"NU.°GIŠ°KIRI₆": "gardener", "Ausgebildeter": "trained man", "Ausgebildete": "trained woman", "(Heilpflanze)": "(a medicinal plant)",
"Köcher": "quiver", "zuteilen": "allot", "stolzieren(?)": "strut(?)", "morgens": "in the morning", "siebenmal": "seven times",
"anreden": "address", "Wacholder": "juniper", "Maßeinheit": "unit of measure", "Alaun": "alum", "Kessel": "cauldron",
"Behälter": "container", "(Frucht)": "(a fruit)", "Nachkomme": "descendant", "Koch": "cook", "Pfeil": "arrow",
"(Pistazienart)": "(a kind of pistachio)", "runde Scheibe": "round disc", "Donut": "ring-shaped bread", "zehn": "ten",
"(Fleisch-)Suppe": "(meat) soup", "Granatapfel(baum)": "pomegranate (tree)", "Nordwind": "north wind", "21": "21",
"Ton": "clay", "Gecko": "gecko", "Eidechse": "lizard", "bunt": "multicoloured", "Kornelkirschbaum": "cornelian cherry tree",
"14": "14", "Gebräu(?)": "brew(?)", "Stößel": "pestle", "Mörser": "mortar", "erscheinen": "appear", "gegen": "against",
}
