# English renderings of TLHdig's German glosses (batch 3).
G = {
"sich wohlbefinden": "be well", "demnach": "accordingly", "gemäß": "according to", "entscheiden": "decide",
"seitlich": "lateral", "Vorhang": "curtain", "lebend": "living", "Glied": "limb", "Stücke": "pieces", "Enkel": "grandchild",
"Asche": "ash", "Herd": "hearth", "Rad": "wheel", "zürnen": "be angry", "Teil": "part", "Schuh": "shoe",
"am (nächsten) Morgen": "the next morning", "ŠU": "hand (ŠU)", "(Abkürzung für Brotbissen)": "(abbreviation for bread morsels)",
"einmal": "once", "(Reinigungsgefäß)": "(a purification vessel)", "treiben": "drive", "Feld": "field", "Korb": "basket",
"(Gewand)": "(a garment)", "schöpfen": "draw (water)", "Halsschlagader": "carotid artery", "Opfertier": "sacrificial animal",
"Krokus(?)": "crocus(?)", "‚meine Sonne‘": "'My Sun' (His Majesty)", "einst": "once, formerly", "überaus": "exceedingly",
"hin-": "thither-", "fortbringen": "carry away", "besprechen": "conjure, recite over", "überschreiten": "cross over",
"(kultisch reines Gefäß)": "(a ritually pure vessel)", "sich verneigen": "bow", "trocknen": "dry", "(Bauelement)": "(a building element)",
"Leichenverbrennungsplatz": "cremation site", "ewig": "eternal", "weibliche Götter": "female gods", "Aufseher": "overseer",
"schwer/Würdenträger": "heavy / dignitary", "tausend": "thousand", "beschützen": "protect", "umliegend": "surrounding",
"wohl": "probably, well", "später": "later", "wachen": "keep watch", "Festung": "fortress", "hohe Priesterin": "high priestess",
"(Flächenmaß)": "(unit of area)", "besänftigen": "appease", "(weibliches) Jungschaf": "ewe lamb", "Werk": "work",
"(Art Getreide)": "(a kind of cereal)", "Fisch(?)": "fish(?)", "blutig machen": "make bloody", "erwachsen": "adult",
"junger erwachsener Mann": "young man", "Geschrei": "outcry", "(alkoholisches Getränk)": "(an alcoholic drink)",
"abseits": "aside", "Hebamme": "midwife", "Fels": "rock", "50": "50", "feucht": "moist", "Gerste": "barley", "sauer": "sour",
"15": "15", "blasen": "blow", "sich drehen": "turn around", "Löwenmann": "lion-man (cult functionary)", "Löwe": "lion",
"Wolf": "wolf", "Wolfmann": "wolf-man (cult functionary)", "hin-/ausbreiten": "spread out", "herschicken; hertreiben": "send here; drive here",
"(Fest)": "(a festival)", "göttliche Führung": "divine guidance", "zusammen": "together", "Mitte": "middle", "Familie": "family",
"Orakel befragen": "consult an oracle", "Magd": "maid", "zur Sklavin machen": "enslave", "schwarz machen": "blacken",
"(Tier)": "(an animal)", "formen(?)": "shape(?)", "Wäscher": "washerman", "Getreide": "grain",
"(Vogel oder seine Nachbildung aus Silber)": "(a bird or its silver replica)", "(Kultfunktionär)": "(a cult functionary)",
"zerstückeln": "cut into pieces", "(ERG) Glied": "limb (ergative)", "Feldzug": "campaign", "Nadel(?)": "needle(?)",
"gepflügtes Feld": "ploughed field", "Ehefrau": "wife", "(Metallgegenstand)": "(a metal object)",
"zu šarikuwa-Truppen gehörig": "of the šarikuwa-troops", "Band": "band, ribbon", "Zeit": "time", "Feige(nbaum)": "fig (tree)",
"hinten": "behind", "nach": "after, to", "nach-": "after-", "(ERG) Unreinheit": "impurity (ergative)", "belasten": "burden",
"erarbeiten": "earn by work", "entlang": "along", "verbrennen": "burn", "schälen": "peel", "Hornist": "horn-blower",
"tief": "deep", "(ver)graben": "bury", "richtig": "right, correct", "Vulva(?)": "vulva(?)", "Schlechter": "bad one",
"Hund": "dog", "Hacke": "hoe", "Leintuch": "linen cloth", "(niederer) Offizier": "(junior) officer", "(Heilkraut)": "(a medicinal herb)",
"nüchtern(?)": "sober, fasting(?)", "auf Hurritisch": "in Hurrian", "Palast": "palace", "zerstampfen": "crush",
"soviel machen(?)": "make so much(?)", "gesehen werden": "be seen", "sieben": "seven", "Tontafelschreiber": "tablet scribe",
"von alters her": "from of old", "sich fürchten": "be afraid", "preisen": "praise", "höher": "higher", "erreichen": "reach",
"göttliches Walten": "divine agency", "schütteln": "shake", "Vertrag": "treaty", "dort": "there",
"sich niederwerfen": "prostrate oneself", "warum?": "why?", "Dörrfleisch": "dried meat", "Zeitpunkt": "moment",
"Namtaru (Dämon)": "Namtaru (demon)", "Zeugenschaft": "witness", "unterirdischer Wasserlauf": "underground watercourse",
"stützen": "support", "zahlreich werden": "become numerous", "Beute": "booty", "stark werden": "become strong",
"zornig": "angry", "Nest(?)": "nest(?)", "abzählen": "count off", "20mal": "20 times", "Stirnreif": "diadem",
"getrennt": "separate", "‚Wasserstein‘": "'water stone'", "(Festtagsgewand des Königs)": "(king's festival garment)",
"in guter Absicht": "with good intent", "Nacht (vergöttlicht)": "Night (deified)", "gelb machen": "make yellow", "+n": "+n",
"Prinz": "prince", "Umhang": "cloak", "Streitwagen": "chariot", "Kopfbedeckung": "head covering", "niederschlagen": "strike down",
"schlachten": "slaughter", "beschwören": "conjure", "beendigen": "finish", "Substitutsstatus": "substitute status",
"SA₅": "red (SA₅)", "Tuchgürtel": "cloth belt", "jagen": "hunt", "verschwinden lassen": "make disappear", "vorne": "in front",
"an vorderster Stelle": "in first place", "schwanger": "pregnant", "schwanger sein": "be pregnant", "regelmäßig": "regular",
"(ERG) Böses": "evil (ergative)", "beständig": "constant", "(Gebäckssorte)": "(a kind of pastry)", "40": "40",
"Kichererbse": "chickpea", "(Gefäß mit einer) Bierart": "(vessel of) a kind of beer", "Apfel(baum)": "apple (tree)",
"Ziege": "goat", "Mischkrug(?)": "mixing jar(?)", "Opferschale": "offering bowl", "Libationsgefäß": "libation vessel",
"hundert": "hundred", "(ERG) Platz": "place (ergative)", "überqueren lassen": "let cross", "Suppe": "soup, stew",
"Rüstigkeit": "vigour", "Tür": "door", "Löwenstatue(?)": "lion statue(?)", "taub": "deaf", "taub machen": "make deaf",
"Sehen": "sight", "vollständig": "complete", "Speer": "spear", "erlöschen": "go out, be extinguished", "zusammen-": "together-",
"berühren": "touch", "lecken": "lick", "versorgen": "provide for", "neben": "beside", "angemessen": "appropriate",
"die Brust gebend": "giving the breast", "von jener Seite": "from that side", "Zauberei": "sorcery", "Zeugung": "procreation",
"REF2": "REF2 (particle)", "Becken(?)": "basin(?)", "Ohr-Symbol": "ear symbol", "Weisheit": "wisdom",
"(ERG) Sehne": "sinew (ergative)", "degradieren": "degrade", "(ERG) Hand": "hand (ergative)", "Hunger": "hunger",
"entwirren(?)": "untangle(?)", "links": "left", "links von": "left of", "linker": "left", "Länge": "length", "lang": "long",
"šarikuwa-Truppen": "šarikuwa-troops", "Stellvertreter": "substitute", "zum Sündenbock werden": "become a scapegoat",
"Finger (auch als Längenmaß)": "finger (also a length measure)", "Liste": "list", "erregen": "stir up", "besetzt": "occupied",
"Kapuze": "hood", "Gürtel(?)": "belt(?)", "(Decke, ein Tuch, eine Stola)": "(a cover, cloth or stole)",
"(Ohren mit Wolle) verstopfen": "stop up (ears with wool)", "Lamm": "lamb", "Abend": "evening", "dämmern": "dawn, dusk",
"(Maß)": "(a measure)", "Kuh": "cow", "böse werden": "turn evil", "Wacholderbaum": "juniper", "ungünstig": "unfavourable",
"Pfropf (aus Wolle)": "plug (of wool)", "brechen": "break", "Sichel": "sickle", "Grausamkeit(?)": "cruelty(?)",
"(her)schicken": "send (here)", "Rückstand": "residue, arrears", "frisch": "fresh", "rein": "pure", "(sich) reinigen": "purify (oneself)",
"(Gebäude)": "(a building)", "blutrot": "blood-red", "Urenkel": "great-grandchild", "(großer Vogel)": "(a large bird)",
"Ordnung": "order", "Oberhaupt": "chief", "Jahr; zum Jahr gehörig": "year; yearly", "jung": "young", "Jungtier": "young animal",
"abgeschnittener Stoff": "cut cloth", "(Getreidesorte)": "(a kind of grain)", "Rohrarbeiter": "reed-worker",
"aus Rohrgeflecht": "of wickerwork", "sechzig": "sixty", "Feinöl": "fine oil", "Gericht": "court; dish", "Tischmann": "table-man (server)",
"Schenkel(?)": "thigh(?)", "Sänger": "singer", "Knie": "knee", "süß": "sweet", "Süßbrot": "sweet bread",
"(kleine Mengenangabe)": "(a small quantity)", "Milch": "milk", "(Wollgegenstand)": "(a woollen object)", "liegen": "lie",
"toben": "rage", "weich": "soft", "Halt machen": "halt", "Gunst": "favour",
}
