# English renderings of TLHdig German glosses (batch 5: glosses reached via the written-form dictionary).
G = {
"Esel": "donkey", "Laubwerk": "foliage", "Becher aus gebranntem Ton": "cup of fired clay", "hinhängen": "hang up",
"Ort": "place", "mit": "with", "Vogelfänger": "fowler", "Bogen": "bow", "verzaubern": "bewitch",
"(Orakelterminus)": "(oracle term)", "überall": "everywhere", "(PAB, scribal mark)": "(PAB, scribal mark)",
"Starrheit": "stiffness", "nebst": "together with", "auf:ADV=CNJctr=OBPs": "on (adv.) + 'but'", "Tablett": "tray",
"Trinkhalm": "drinking straw", "auf!": "up!", "(Tontafeltyp)": "(a tablet type)", "Bezirk": "district",
"Erhebung": "elevation", "Stroh": "straw", "Werkzeug": "tool", "umwinden": "wind around", "hineinstecken": "insert",
"Zeuge": "witness", "luwisch": "Luwian", "schließen": "close", "Arzt": "physician", "freundlich sein": "be friendly",
"sich satt essen": "eat one's fill", "hämmern": "hammer", "Vlies": "fleece", "offene Flamme": "open flame",
"schweigen": "be silent", "abkühlen": "cool down", "schlagen(?)": "strike(?)", "(ab)beißen": "bite (off)", "Lippe": "lip",
"neunmal": "nine times", "LUW.CNJ": "Luwian conjunction", "Nahrung": "food", "bringen": "bring", "zu Häupten": "at the head",
"Greis": "old man", "(Futter)mischung": "(fodder) mixture", "PAL.QUAN.NOM.SG.C": "Palaic quantifier",
"Höhlenente": "shelduck(?)", "Opferschauer": "haruspex", "hervorragend": "excellent", "einfach": "simple",
"Freundlichkeit": "friendliness", "festmachen": "fasten", "Brotgefäß": "bread vessel", "eiförmiger Stein": "egg-shaped stone",
"hin-/ ausbreiten": "spread out", "von": "from", "aufhäufen": "heap up", "glühen": "glow", "Faden": "thread",
"die tuḫš-Handlung vollziehen": "perform the tuḫš- act", "Opfertisch": "offering table", "Torbau": "gatehouse", "Bein": "leg",
"Zicklein": "kid (young goat)", "Eid": "oath", "Hoden": "testicle", "Schwanz": "tail", "Tränenstrom": "flood of tears",
"Straßenbett": "roadbed", "Kultsänger": "cult singer", "Haus oder Raum der (kultischen) Waschung": "house or room of (ritual) washing",
"reisen": "travel", "sich nähern": "approach", "Brauch": "custom", "beten": "pray", "CNJ=PPRO.3SG.D/L": "conj. + 'to him/her'",
"Hälfte": "half", "wohlriechende Pflanze": "fragrant plant", "Gewitter": "thunderstorm", "(Behälter)": "(a container)",
"rechtens": "rightfully", "‘Fuchsvogel’": "'fox-bird'", "Schatten": "shadow", "brennen": "burn", "(ERG) Wacholderbaum": "juniper (ergative)",
"antreiben": "drive on", "in Schrecken geraten": "take fright", "Schlacht": "battle", "übrig bleiben": "remain",
"umfangreich": "extensive", "Kostprobe (einer Opfergabe)": "taste (of an offering)", "anstimmen": "strike up (a song)",
"Abgaben": "dues", "töten": "kill", "Eber": "boar", "72": "72", "vertrocknen": "dry up", "einreiben": "rub in",
"in Gärung versetzen": "ferment", "Verlauf": "course", "Kloß": "dumpling", "Zwiebel": "onion", "n+1": "n+1",
"ruhmreich": "glorious", "Brotstück": "piece of bread", "Räucherbecken": "censer", "Schildkröte": "tortoise",
"zur Verbeugung veranlassen": "make bow", "Wollbüschel": "tuft of wool", "Spindel": "spindle", "Joch": "yoke",
"Kultstele": "cult stele", "neu": "new", "Anrufung": "invocation", "rechts von": "right of", "Altar": "altar", "Kiste": "box",
"Thron": "throne", "derselbe": "the same", "Getreidegottheit": "Grain-deity", "Fackel": "torch", "Aufzeichnung": "record",
"Zahl": "number", "Wildziege": "wild goat", "Hof": "courtyard", "(Baum und sein Holz)": "(a tree and its wood)",
"Pflug": "plough", "(Funktionär)": "(a functionary)", "PAL.REL.ACC.SG.N": "Palaic relative pronoun", "roh": "raw",
"Vogelschauer": "augur", "26": "26", "Schnur": "cord", "kundtun": "make known", "bekämpfen": "fight", "insgesamt": "in all",
"Dattelpalme": "date palm", "Hirsch": "stag", "Ḫurri": "Ḫurri (bull of the Storm-god)",
}
