# English renderings of TLHdig's German glosses (batch 2).
G = {
"Lapislazuli": "lapis lazuli", "Name": "name", "nachholen": "make up for", "Krankheit/Kranker": "illness / sick person",
"Nachtwache": "night watch", "verflechten": "intertwine", "mächtig sein": "be powerful",
"vom/im ungünstigen (Bereich)": "from/in the unfavourable (zone)", "entgegen-": "towards-", "Hirschgott": "Stag-god",
"Feldlager": "army camp", "bestreichen": "smear, coat", "Hundemann": "dog-man (cult functionary)",
"auf den Weg bringen": "send on the way", "herschicken; herfahren": "send here; drive here", "Innengemach": "inner chamber",
"Weizen(?)": "wheat(?)", "fünf": "five", "Totengeist": "spirit of the dead", "Zelt": "tent", "Stiel": "stalk, handle",
"bitten": "ask, pray", "aus": "out of", "Richtigkeit": "correctness", "wenig werden": "diminish",
"(ERG) Wort": "word (ergative)", "Sterben": "dying, death", "männliche Götter": "male gods", "Verdickung(?)": "thickening(?)",
"Feuer": "fire", "Gottesmutter": "Mother-goddess", "Hohlmaß (sūtu)": "dry measure (sūtu)", "drinnen": "inside",
"dreimal": "three times", "(Körperteil)": "(a body part)", "sich gegenseitig bekämpfen": "fight one another",
"vollendet": "completed", "zu Ende gehen": "come to an end", "rechts; günstig": "right; favourable", "reiben": "rub",
"Eibe(?)": "yew(?)", "grollen": "be angry", "gut sein": "be good", "(Holzgegenstand)": "(a wooden object)",
"Ornat; Arbeit": "vestment; work", "Arbeit": "work", "kochen": "cook, boil", "Stier": "bull", "Rinderstall": "cattle pen",
"Messer": "knife", "leben": "live", "Königin": "queen", "Soldatenbrot": "soldier bread", "Türangel": "door pivot",
"Zauberei ausübend": "practising sorcery", "Öl": "oil", "Wimper": "eyelash", "(Messgefäß)": "(a measuring vessel)",
"unrein sein": "be impure", "Kohlenpfanne": "brazier", "Rührkuchen": "batter cake", "Muttergöttin": "Mother-goddess",
"Gerstenbrei": "barley porridge", "Schekel": "shekel", "wissen": "know", "bauen": "build", "Untergang": "setting, downfall",
"eilends": "quickly", "richtig machen": "make right", "günstig werden": "become favourable", "Recht": "law, right",
"jener": "that", "nicht!": "not!", "binden": "bind", "finden": "find", "scharfe Spitze": "sharp point", "Sitz": "seat",
"abschneiden": "cut off", "Platz": "place", "Kriegsgefangener": "prisoner of war", "Leibwächter": "bodyguard",
"Eingeweide": "entrails", "‚Flachbrot‘": "'flat bread'", "Leder": "leather", "Mondgott": "Moon-god", "30": "30",
"steinig": "stony", "unterer": "lower", "Schafbock": "ram", "Finger": "finger", "gießen": "pour",
"Pflanzenknolle": "plant bulb, tuber", "Fußbank(?)": "footstool(?)",
"die Krankheit der Išḫara bekommen": "contract the illness of Išḫara", "bespringen": "mount (of animals)",
"aufteilen": "divide up", "Statue": "statue", "Diener": "servant", "einschnüren": "tie up", "Krampf": "cramp",
"(Eid beim) Leben": "(oath by) life", "kompensieren": "compensate", "Schoß": "lap", "anderer": "other", "hinauf-": "up-",
"inmitten": "amid", "Schale": "bowl", "Malz": "malt", "Prozess": "lawsuit", "Schöpfgefäß": "ladle, dipper",
"die Runde machen": "make the rounds", "zweimal": "twice", "Frucht": "fruit", "sechs": "six", "Wachs": "wax",
"mit Wachs gefüllt": "filled with wax", "stark": "strong", "Meer": "sea", "baden": "bathe", "Teig": "dough",
"Schreck": "fright", "Adler": "eagle", "kaufen": "buy", "(Baum)": "(a tree)", "Stuhl": "chair", "erkranken": "fall ill",
"filtern": "strain, filter", "Pflanze": "plant", "früherer": "former", "jeder": "each", "wünschen": "wish",
"Schmach(?)": "disgrace(?)", "lösen": "release, loosen", "böse(?)": "evil(?)", "Galle(nblase)": "gall (bladder)",
"wachsen": "grow", "Vogel": "bird", "folgendermaßen": "as follows", "SÍG": "wool (SÍG)",
"Aprikose(nbaum)": "apricot (tree)", "Mispel(?)": "medlar(?)", "(Stein)": "(a stone)", "viermal": "four times",
"30mal": "30 times", "rote Wolle": "red wool", "sich pflegen": "take care of oneself", "Dienerin": "maidservant",
"Schlechtigkeit": "wickedness", "hell werden": "become light, dawn", "Rohr": "reed, cane", "Flügel": "wing",
"Tablett (aus Rohr)": "tray (of reed)", "Ehemann": "husband", "(Toilettenartikel)": "(a toiletry)", "(Pflanze)": "(a plant)",
"Schärpe(?)": "sash(?)", "früherer Zustand": "former state", "Dienstbarkeit": "servitude", "20": "20",
"zum Schwören veranlassen": "make swear an oath", "Utima (Abk.)": "Utima (abbr.)", "(ab)ernten": "harvest",
"nicht (volitiv)": "not (volitive)", "Rücken": "back", "Fluß": "river", "wichtig": "important",
"Kompensation": "compensation", "n": "n", "(unbekannte Zahl)": "(unknown number)", "gut machen": "make good",
"(weibliches) Schaf": "ewe", "noch nicht": "not yet",
"(dekoratives Element aus Gold oder Silber)": "(decorative element of gold or silver)", "Gut": "property, goods",
"Säule": "pillar", "mit ašuša- versehen": "fitted with ašuša-", "grün": "green", "laufen lassen": "let run",
"grüne Wolle": "green wool", "(kleiner Steingegenstand)": "(a small stone object)", "(Orakelvogel)": "(an oracle bird)",
"Nachbildung": "replica", "Bierwürze": "beer wort", "Linse": "lentil", "Fußschemel": "footstool", "vorderster": "foremost",
"Monat": "month", "öffnen": "open", "Rippe": "rib", "hell": "bright", "warmes Brot": "warm bread", "günstig": "favourable",
"Horn": "horn", "(kultisches Getränk)": "(a cultic drink)", "Rosine(n)": "raisin(s)", "Kupfer": "copper", "Welpe": "puppy",
"Welpenmann": "puppy-man (cult functionary)", "Topf": "pot", "magisches Ritual": "magic ritual", "Kupfererz": "copper ore",
"Bett": "bed", "schneiden": "cut", "fließen": "flow", "Zahn": "tooth", "aufständisch": "rebellious",
"(nach) draußen": "(to the) outside", "Zweig": "branch, twig", "Augenbraue": "eyebrow", "Schaufel": "shovel",
"Talg": "tallow", "Stein": "stone", "schrubben(?)": "scrub(?)", "Holz": "wood", "Tal": "valley", "Eisen": "iron",
"Spross": "shoot, sprout", "‘Meine Sonne’": "'My Sun' (His Majesty)", "(ist) nicht (vorhanden)": "(is) not (present)",
"Gold": "gold", "Erregung": "agitation", "erfrischen": "refresh", "Fleisch": "meat, flesh", "schädigen": "harm",
"leer": "empty", "suchen/reinigen": "seek / purify", "(ERG) Blut": "blood (ergative)", "königlicher Status": "royal status",
"hinsetzen": "set down", "Reizung(?)": "irritation(?)", "zehnmal": "ten times", "walḫi-Bier": "walḫi-beer",
"Laub": "foliage", "Ziegenbock": "billy goat", "stechen": "pierce, sting", "Gesamtheit": "totality",
"Zahn aus Holz": "wooden tooth", "Last": "load", "Böses tun": "do evil", "hinunter": "down", "hinab zu": "down to",
"Seite": "side", "anheften": "attach", "Brust": "breast, chest", "(Blume)": "(a flower)", "Gamasche": "gaiter",
"Kamm": "comb", "Leber": "liver", "unrein machen": "make impure", "(hin)treiben": "drive (there)", "Schwein": "pig",
"Schweinehirt": "swineherd", "Honig": "honey", "entsprechen": "correspond", "Fisch": "fish", "Mutter": "mother",
"Wagen": "wagon, chariot", "Länder": "lands", "Schlinge": "snare, noose", "(hattischer Zuruf)": "(a Hattic acclamation)",
"Königtum": "kingship", "ganz und gar": "completely", "feindlich werden": "become hostile", "am Leben erhalten": "keep alive",
"befehlen": "command", "in reinem Zustand": "in a pure state", "Nadel": "needle", "leben lassen": "let live",
"festdrücken": "press firmly", "Bevölkerung": "population", "zum zweiten Mal": "for the second time",
"zerstoßen": "crush, pound", "oberer": "upper", "verschwinden(?)": "disappear(?)", "Gabe": "gift", "schwer machen": "make heavy",
"Stirn": "forehead", "sorgen für": "care for", "After": "anus", "(kostbares Gewand)": "(a precious garment)",
"(kostbare Gewänder)": "(precious garments)", "Güte": "goodness", "Schlag": "blow, stroke", "rachsüchtig(?)": "vengeful(?)",
"Bekämpfung": "combatting", "Fieber(?)": "fever(?)", "Wiese": "meadow", "(Krankheit des Kopfes)": "(an illness of the head)",
"Saubohne": "broad bean", "Sohn": "son", "Tochter": "daughter", "günstig sein": "be favourable", "Mine": "mina",
"Butterschmalz": "ghee, clarified butter", "acht": "eight", "Weißdorn": "hawthorn", "Getränk": "drink",
"(Trinkgefäß)": "(a drinking vessel)", "zudecken": "cover up", "nah": "near", "zusammenfügen": "join together",
"hoch": "high", "Gesalbter": "anointed one",
}
